## Numpy Array Operations

In [1]:
import numpy as np

In [5]:
arr = np.arange(1, 13)
print("Original Array:\n", arr)

print("Basic Slicing: ", arr[2:8])
print("Slicing with Step: ", arr[1:10:2])
print("Negative Indexing: ", arr[-5:-1])

Original Array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
Basic Slicing:  [3 4 5 6 7 8]
Slicing with Step:  [ 2  4  6  8 10]
Negative Indexing:  [ 8  9 10 11]


### Indexing in 2D array

In [9]:
arr_2D = arr.reshape(3, 4)
print("2D Array:\n", arr_2D)
print("Row 2; column 3 element:", arr_2D[1, 2])
print("Row 1:", arr_2D[0, :])
print("Column 2:", arr_2D[:, 1])


2D Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Row 2; column 3 element: 7
Row 1: [1 2 3 4]
Column 2: [ 2  6 10]


### Sorting

In [ ]:
unsorted = np.array([3, 1, 4, 2, 5])
print("Unsorted : ", unsorted)
print("Sorted (Ascending): ", np.sort(unsorted))

arr_2D = np.array([[3, 1, 4], [2, 5, 6], [9, 8, 7]])
print("Original 2D Array:\n", arr_2D)
print("Sorted 2D Array (by rows):\n", np.sort(arr_2D, axis=1)) # Important
print("Sorted 2D Array (by columns):\n", np.sort(arr_2D, axis=0))

Unsorted :  [3 1 4 2 5]
Sorted (Ascending):  [1 2 3 4 5]
Original 2D Array:
 [[3 1 4]
 [2 5 6]
 [9 8 7]]
Sorted 2D Array (by rows):
 [[1 3 4]
 [2 5 6]
 [7 8 9]]
Sorted 2D Array (by columns):
 [[2 1 4]
 [3 5 6]
 [9 8 7]]


### Filtering

In [19]:
numbers = np.array([1, 2, 3, 4, 5, 6])
print("Original Array:", numbers)

# filtered = numbers[numbers > 3] # condition at indexing
# Store expression as a mask in a variable
mask = numbers > 3
filtered = numbers[mask]
print("Filtered Array (elements > 3):", filtered)

Original Array: [1 2 3 4 5 6]
Filtered Array (elements > 3): [4 5 6]


### Fancy indexing vs np.where()

In [25]:
indices = [0, 2, 4]
print("Numbers :", numbers[indices])

where_res = np.where(numbers > 3)   # Returns indices where condition is True
print("Where result:", where_res)
print("Fancy Indexing Result:", numbers[where_res])

Numbers : [1 3 5]
Where result: (array([3, 4, 5]),)
Fancy Indexing Result: [4 5 6]


In [32]:
# if condition is True → pick x  
# else → pick y

# condition_arr = np.where(numbers > 3, numbers, numbers)
condition_arr = np.where(numbers > 3, "True", "False")
print("Condition Array (elements > 3):", condition_arr)

Condition Array (elements > 3): ['False' 'False' 'False' 'True' 'True' 'True']


### Adding and Removing Data

In [36]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])
print("Array 1:", arr1)
print("Array 2:", arr2)

# Not to do "arr1 + arr2" --> Matrix addition
print("Concatenated Array:", np.concatenate((arr1, arr2)))

Array 1: [1 2 3 4 5]
Array 2: [ 6  7  8  9 10]
Concatenated Array: [ 1  2  3  4  5  6  7  8  9 10]


### Array Compatibility

In [39]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
print("Array a:", a)
print("Array b:", b)
print("Array c:", c)

print("Compatibility Shape:", a.shape == b.shape, b.shape == c.shape)

Array a: [1 2 3]
Array b: [4 5 6]
Array c: [7 8 9]
Compatibility Shape: True True


In [46]:
original = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original Array:\n", original)

new_row = np.array([10, 11, 12])
# Adding a new row to the original array --> using np.vstack
# Note: The new row must have the same number of columns as the original array
modified = np.vstack((original, new_row))
print("Modified Array:\n", modified)

new_col = np.array([[13], [14], [15]])
# Adding a new column to the original array --> using np.hstack
# Note: The new column must have the same number of rows as the original array
modified = np.hstack((original, new_col))
print("Modified Array with New Column:\n", modified)

Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Modified Array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Modified Array with New Column:
 [[ 1  2  3 13]
 [ 4  5  6 14]
 [ 7  8  9 15]]


In [48]:
arr = np.array([1, 2, 3, 4, 5])
print("Original Array:", arr)
deleted = np.delete(arr, 2)  # Deletes the element at index 2
print("Array after Deletion:", deleted)

deleted = np.delete(arr, [1, 3])  # Deletes elements at indices 1 and 3
print("Array after Deletion of Multiple Elements:", deleted)

Original Array: [1 2 3 4 5]
Array after Deletion: [1 2 4 5]
Array after Deletion of Multiple Elements: [1 3 5]
