## Numpy Array and Basics
Numpy Begins!

In [1]:
import numpy as np

In [2]:
## Creating array from list
array_1D = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1D)

1D Array: [1 2 3 4 5]


In [3]:
array_2D = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", array_2D)

2D Array:
 [[1 2 3]
 [4 5 6]]


### List vs numpy array

In [4]:
py_list = [1, 2, 3, 4, 5]
print("Python List Multiplied by 2:", py_list * 2)

Python List Multiplied by 2: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [ ]:
NP_array = np.array([1, 2, 3, 4, 5])

# SCALAR MULTIPLICATION
print("Numpy Array Multiplied by 2:", NP_array * 2)

Numpy Array Multiplied by 2: [ 2  4  6  8 10]


#### Speed Test

In [8]:
import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
end = time.time()
print("Python List Time:", (end - start))

start = time.time()
NP_array = np.arange(1000000)*2
end = time.time()
print("Numpy Array Time:", (end - start))

Python List Time: 0.06588315963745117
Numpy Array Time: 0.005000114440917969


### Creating array from scratch

In [16]:
zeros = np.zeros((3, 4))   # Dimensions 3x4 filled with zeros
ones = np.ones((2, 5))     # Dimensions 2x5 filled with ones
print("Zeros Array:\n", zeros)
print("Ones Array:\n", ones)

full = np.full((2, 3), 7)  # Dimensions 2x3 filled with the value 7
print("Full Array:\n", full)

# Important
randm = np.random.random((2, 3))  # Random values in a 2x3 array
print("Random Array:\n", randm)

# Non-inclusive outer boundary
sequence = np.arange(10)  # Array with values from 0 to 9
print("Sequence Array:", sequence)
sequence = np.arange(1, 10)  # Array with values from 1 to 9
print("Sequence Array from 1 to 9:", sequence)
sequence = np.arange(1, 10, 2)  # Array with values from 1 to 9 with step of 2
print("Sequence Array with step of 2:", sequence)

rand_int = np.random.randint(1, 10, (2, 3))
print("Random Integer Array:\n", rand_int)


Zeros Array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Full Array:
 [[7 7 7]
 [7 7 7]]
Random Array:
 [[0.61619239 0.04662978 0.77913793]
 [0.48290214 0.92095822 0.26482263]]
Sequence Array: [0 1 2 3 4 5 6 7 8 9]
Sequence Array from 1 to 9: [1 2 3 4 5 6 7 8 9]
Sequence Array with step of 2: [1 3 5 7 9]
Random Integer Array:
 [[5 1 7]
 [8 3 7]]


### Vector, Matrix and Tensor


In [19]:
vector = np.array([1, 2, 3])  # 1D array
print("Vector (1D Array):", vector)

matrix = np.array([[1, 2, 3], [4, 5, 6]])  # 2D array
print("Matrix (2D Array):\n", matrix)
  
# A 3D array or higher dimension is called a tensor in numpy 
tensor = np.array([
    [[1, 2], [3, 4]], 
    [[5, 6], [7, 8]]
])  # 3D array

print("Tensor (3D Array):\n", tensor)

Vector (1D Array): [1 2 3]
Matrix (2D Array):
 [[1 2 3]
 [4 5 6]]
Tensor (3D Array):
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [23]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Original Array:\n", arr)
print("Array Properties:")
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Data Type:", arr.dtype)
print("Number of Dimensions:", arr.ndim)

Original Array:
 [[1 2 3]
 [4 5 6]]
Array Properties:
Shape: (2, 3)
Size: 6
Data Type: int64
Number of Dimensions: 2


### Array reshaping

In [29]:
arr = np.arange(10)
print("Original Array:", arr)

reshaped_arr = arr.reshape((2, 5))  # Reshape to 2 rows and 5 columns
print("Reshaped Array:\n", reshaped_arr)

flattened_arr = reshaped_arr.flatten()  # Flatten the array to 1D
print("Flattened Array:", flattened_arr)

# Returns views instead of copies
raveled_arr = reshaped_arr.ravel()  # Ravel the array to 1D
print("Raveled Array:", raveled_arr)

# Transpose the array
transposed_arr = reshaped_arr.T  # Transpose the array
print("Transposed Array:\n", transposed_arr)

Original Array: [0 1 2 3 4 5 6 7 8 9]
Reshaped Array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Flattened Array: [0 1 2 3 4 5 6 7 8 9]
Raveled Array: [0 1 2 3 4 5 6 7 8 9]
Transposed Array:
 [[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
